services:
  xxtlancontrol:
    image: ${IMAGE:-ghcr.io/havonz/xxtlancontrol}:${TAG:-latest}
    container_name: xxtlancontrol
    restart: unless-stopped
    # Use host networking
    network_mode: host
    environment:
      DATA_DIR: /app/data
      UDP_LISTEN_PORT: ${UDP_LISTEN_PORT:-31500}
      HTTP_LISTEN: :${HTTP_PORT:-46990}
      ADVERTISE_API_URL: ${ADVERTISE_API_URL:-}
    volumes:
      - ${DATA_DIR_HOST:-./xxtlancontrol-data}:/app/data
